---
title: "Policies"
---

```{r, include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
```

### Academic Integrity

Penn State defines academic integrity as the pursuit of scholarly activity in an open, honest and responsible manner. All students should act with personal integrity, respect others dignity, rights and property, and help create and maintain an environment in which all can succeed through the fruits of their efforts (Faculty Senate Policy 49-20). Sanctions for academic misconduct can include a grade of F for the course as well as other penalties.

Students are responsible for maintaining academic integrity.  Violations include cheating on exams, talking to others during exams, looking at another student's test materials or answers during an exam, removing exams from the classroom without consent from the instructor, plagiarizing (do not copy from someone else!), and dishonesty in any aspect of course participation.

When you complete assignments, remember the **ABC**s to avoid plagiarism: **A**lways place copied information within quotation marks, include information about the quoted or paraphrased source in a **B**ibliography, and **C**ite the source in the body (in the text) of your paper immediately after the quoted or paraphrased information. When in doubt, cite in the text and include the source in a bibliography.

### Late, missed or make-up assignments

#### Exams

Make-up exams may be permitted under unusual circumstances such as (a) an interview for graduate school or a job, (b) illness, (c) religious observance, (d) the death of a family member, or (e) any other event recognized by the university as a valid excuse for absence from class.

If you must miss class on the day an exam is scheduled, you must do the following:

1. Contact the TA or the instructor by telephone, email, or in person in advance of the exam. Twenty-four hours notice is expected. If you do not contact the TA or instructor in advance, it is possible that you may not be able to schedule a make-up exam.
2. Arrange with the TA or instructor to take a make-up exam as soon as possible, but no later than one (1) week following the date of the scheduled exam. It is your responsibility, not the TA's or the instructor's to schedule an approved make-up exam in a timely way.

#### Quizzes

No make-up quizzes will be given except under unusual circumstances. 
You may ask for a copy of the quiz for studying purposes, however.

#### Accommodation for persons with disabilities

Penn State welcomes students with disabilities into the University's educational programs. Please refer to the information provided by Student Disability Resources (SDR) at <http://equity.psu.edu/student-disability-resources/> for information about the procedures required to obtain reasonable accommodations in this course. 
Students should discussSDR-approved accommodations with their instructor as early in the semester as possible, even if they have taken another course with the instructor. 
Please note: students are not required to provide their instructor with information about the nature of their condition.
 
Penn State students are also welcome to contact other units for assistance with personal concerns that interfere with academic progress, including: Counseling and Psychological Services (CAPS; <http://studentaffairs.psu.edu/counseling/>), the Office of Student Affairs (<http://studentaffairs.psu.edu/>), Career Services (<http://studentaffairs.psu.edu/career/>), the Center for Women Students (<http://studentaffairs.psu.edu/womenscenter/>), the LGBTQA Student Resource Center (<http://studentaffairs.psu.edu/lgbtqa/>), the Office of Sexual Misconduct
Prevention and Response (<http://titleix.psu.edu/>), Penn State Educational Equity (<http://equity.psu.edu/>), the Multicultural Resource Center (<http://equity.psu.edu/mrc>), and University 
Health Services (<http://studentaffairs.psu.edu/health/>).

### Nondiscrimination Statement

The Pennsylvania State University is committed to equal access to programs, facilities, admission and employment for all persons. 
It is the policy of the University to maintain an environment free of harassment and free of discrimination against any person because of age, race, color, ancestry, national origin, religion, creed, service in the uniformed services (as defined in state and federal law), veteran status, sex, sexual orientation, marital or family status, pregnancy, pregnancy-related conditions, physical or mental disability, gender, perceived gender, gender identity, genetic information or political ideas.  
Discriminatory conduct and harassment, as well as sexual misconduct and relationship violence, violates the dignity of individuals, impedes the realization of the University's educational mission, and will not be tolerated.
 
Direct all inquiries regarding the nondiscrimination policy to:
 
Dr. Kenneth Lehrman III</br>
Vice Provost for Affirmative Action</br>
Affirmative Action Office</br>
The Pennsylvania State University</br>
328 Boucke Building</br>
University Park, PA 16802-5901</br>
Email: kfl2@psu.edu</br>
Tel (814) 863-0471

### Diversity Statement

This classroom is a place where you will be treated with respect. 
All members of this class are expected to contribute to a respectful, welcoming and inclusive environment for every other member of the class.  
Penn State is committed to creating an educational environment which is free from intolerance directed toward individuals or groups and strives to create and maintain an environment that fosters respect for others as stated in Policy AD29 Statement on Intolerance.
 
### Mandated Reporting Statement

Penn State's policies require me, as a faculty member, to share information about incidents of sex-based discrimination and harassment (discrimination, harassment, sexual harassment, sexual misconduct, dating violence, domestic violence, stalking, and retaliation) with Penn State's Title IX coordinator or deputy coordinators, regardless of whether the incidents are stated to me in person or shared by students as part of their coursework. 
For more information regarding the University's policies and procedures for responding to reports of sexual or gender-based harassment or misconduct, please visit <http://titleix.psu.edu>.
 
Additionally, I am required to make a report on any reasonable suspicion of child abuse in accordance with the Pennsylvania Child Protective Services Law.

### COVID safety information

Students experiencing any illness and especially COVID-19 related symptoms should not attend class in person. 
Those students are strongly encouraged to contact a health care provider and their instructor as soon as possible to discuss reasonable accommodations.  

Students should remain at least six feet away from others in our classroom. 
Policies require all of us to wear masks appropriately to cover our mouths and noses while we are in our classroom. 
Students who do not want to distance themselves appropriately or wear a mask during class may not attend class in person. 
Attending this class without wearing a mask properly constitutes a classroom disruption, a violation of several articles of the student Code of Conduct (https://studentaffairs.psu.edu/support-safety-conduct/student-conduct/code-conduct), and a violation of policy AD 57 (https://policy.psu.edu/policies/ad57). 
Anyone in the classroom who is not wearing a mask appropriately will be asked to do so or to leave. 
I am required to end class if anyone refuses this request. 
Failure to comply may result in a conduct violation. 
Students who believe they should be granted a health or safety exception to this policy should consult with Student Disability Resources about reasonable accommodations and present their accommodation letter to me if an exception is granted. 

### Zoom
	
I may decide to use Zoom and record lectures to allow students who are unable to attend class in person to participate.

While you are on Zoom, keep in mind that this is a classroom environment and others should be treated with respect. 
Please keep your microphone muted unless you want to ask a question or interact with someone. 
If your microphone is not muted, the entire class will be able to hear what is going on in your environment. 
As an instructor, I personally like to see people’s faces. 
As a participant, I am more involved when I have my camera on. 
I realize, however, that there are many reasons why you might not want to turn on your camera such as poor internet connection, joining via phone, or other privacy concerns. 
It is your choice as to whether you would like to have the camera on or not.

**Note that video and audio recordings of class lectures may be part of the classroom activity.**

The video and audio recording is used for educational use/purposes and only may be made available to all students presently enrolled in the class. 
For purposes where the recordings will be used in future class session/lectures, any type of identifying information will be adequately removed.
