---
title: "Schedule"
---

*[W&B](http://3e.mindsmachine.com/) refers to the Watson & Breedlove text. Assignments are given in 'chapter:pages' format, e.g., 1:2-19 means read Chapter 1, pages 2-19.*

## Week 1, August 23 - 27

### Tuesday, August 24

- Topics
    - Introduction to the course
    - A bit about systems
- Assignments
    - Read: W&B 1:3-21
- Materials
    - [Slides](lectures/260-2021-08-24-intro.html). [PDF](lectures/260-2021-08-24-intro.pdf)

### Thursday, August 26

- Topics
    - History of neuroscience
    - Levels of analysis
    - Neuroscience methods I
- Assignments
    - Review: <http://www.columbia.edu/cu/psychology/courses/1010/mangels/neuro/history/history.html>
    - Scan: <https://faculty.washington.edu/chudler/hist.html>
    - Read: W&B 1:3-21; 2:29, 48-51; 3:75-79.
    - Watch: [Beautiful 3-D Brain Scans Show Every Synapse](https://youtu.be/nvXuq9jRWKE)
    - Optional:
        - [Grillner, Kozlov, Kotaleski (2005)](http://www.ncbi.nlm.nih.gov/pubmed/16146688)
- Materials
    - [Slides](lectures/260-2021-08-26-history-levels-methods.html). [PDF](lectures/260-2021-08-26-history-levels-methods.pdf)

---

## Week 2, August 30 - September 3

### Tuesday, August 31

- Topics
    - Neuroscience methods II.
- Assignments
    - Read: W&B 1:3-21; 2:29, 48-51; 3:75-79.
    - Watch: [Magnetic Resonance Imaging Explained](https://youtu.be/MiL0wCZr0Mw)
    - Optional: <https://en.wikibooks.org/wiki/Cognitive_Psychology_and_Cognitive_Neuroscience/Behavioural_and_Neuroscience_Methods>
- Materials
    - [Slides](lectures/260-2021-08-31-methods.html). [PDF](lectures/260-2021-08-31-methods.pdf)

### Thursday, September 2

- Topics
    - Neuroanatomy I
- Assignments
    - Read W&B 2:32-47
- Materials
    - [Slides](lectures/260-2021-09-02-anatomy-I.html). [PDF](lectures/260-2021-09-02-anatomy-I.pdf)

---

## Week 3, September 6 - 10

### Tuesday, September 7

- Topics
    - Neuroanatomy II
- Assignments
    - Read W&B 2:32-47 
- Materials
    - [Slides](lectures/260-2021-09-07-anatomy-II.html). [PDF](lectures/260-2021-09-07-anatomy-II.pdf)

### Thursday, September 9

- Topics
    - [**Quiz 1**]()
    - Neuroanatomy III
- Assignments
- Materials
    - [Slides](lectures/260-2021-09-09-anatomy-III.html). [PDF](lectures/260-2021-09-09-anatomy-III.pdf)

---

## Week 4, September 13 - 17

### Tuesday, September 14

- Topics
    - Cells of the nervous system
    - How nerve cells compute (Neurophysiology I)
- Assignments
    - Read W&B: 2:23-32
    - Read W&B: 3:55-59
- Materials
    - [Slides](lectures/260-2021-09-14-cells.html). [PDF](lectures/260-2021-09-14-cells.pdf)

### Thursday, September 16

**NO CLASS**

---

## Week 5, September 20 - 24

### Tuesday, September 21

- Topics
    - Neurophysiology II
    - Exam 1 Review
- Assignments
    - Read W&B: 3:55-70
    - Watch: Video about membrane potentials <https://www.youtube.com/embed/PtKAeihnbv0>
- Materials
    - [Slides](lectures/260-2021-09-21-cells-II.html). [PDF](lectures/260-2021-09-21-cells-II.pdf).
    - [Exam 1 Study Guide](lectures/260-2021-09-21-exam-1-review.html). [PDF](lectures/260-2021-09-21-exam-1-review.pdf).
    
### Thursday, September 23 

- Topics
    - **Exam 1**

---

## Week 6, September 27 - October 1

### Tuesday, September 28

- Topics
    - Neurophysiology III
- Assignments
    - Read W&B 3:70-75
- Materials
    - [Slides](lectures/260-2021-09-28-cells-III.html). [PDF](lectures/260-2021-09-28-cells-III.pdf).

### Thursday, September 30

- Topics
    - Neurochemistry I
- Assignments
    -  Read W&B 4:83-92, 96-100
- Materials
    - [Slides](lectures/260-2021-09-30-neurochem-I.html). [PDF](lectures/260-2021-09-30-neurochem-I.pdf)

---

## Week 7, October 4 - 8

### Tuesday, October 5

- Topics
    - Neurochemistry II
- Assignments
    -  Read W&B 4:83-92, 96-100
- Materials
    - [Slides](lectures/260-2021-10-05-neurochem-II.html). [PDF](lectures/260-2021-10-05-neurochem-II.pdf)

### Thursday, October 7

- Topics
    - Hormones and the brain
    - **Blog post 1 (of 3) due**. | [Assignment details](blog-assignment.html) |
    - **Quiz 2**, available on Canvas *after* class.
- Assignments
    - Read W&B 8:217-234
- Materials
    - [Slides](lectures/260-2021-10-07-hormones.html). [PDF](lectures/260-2021-10-07-hormones.pdf)

---
    
## Week 8, October 11 - 15

### Tuesday, October 12

- Topics
    - Evolution of the human brain.
    - Review for Exam 2
- Assignments
- Materials
    - [Slides](lectures/260-2021-10-12-evolution.html). [PDF](lectures/260-2021-10-12-evolution.pdf)
    - [Exam 2 Study Guide](lectures/260-2021-10-12-exam-2-review.html)

### Thursday, October 14

- Topics
    - **Exam  2**
    
---

## Week 9, October 18 - 22

### Tuesday, October 19

- Topic
    - Psychopathology I: Depression & Bipolar disorder
- Assignments
    - Read W&B 12:361-371
- Materials
    - [Slides](lectures/260-2021-10-19-depression-bipolar.html). [PDF](lectures/260-2021-10-19-depression-bipolar.pdf)
    
### Thursday, October 21

- Topics
    - Psychopathology II: Schizophrenia.
- Assignments
    - Read W&B 12:347-360.
- Materials
    - [Slides](lectures/260-2021-10-21-schizophrenia.html). [PDF](260-2021-10-21-schizophrenia.pdf). 

---

## Week 10, October 25 - 29

#### Tuesday, October 26

- Topics
    - Emotion
    - Happiness & reward
    - Fear & stress
- Assignments
    - Read W&B 11:319-333, 337-344.
- Materials
    - [Slides](lectures/260-2021-10-26-emotion.html). [PDF](lectures/260-2021-10-26-emotion.pdf)

### Thursday, October 28

- Topics
    - **Quiz 3**.
    - Exam 2 returned.

---

## Week 11, November 1 - 5

### Tuesday, November 2

**NO CLASS**

### Thursday, November 4

- Topics
    - Sensory systems
    - Somatosensation
- Assignments
    - **Blog post #2 (of 3) due**. | [Assignment details](blog-assignment.html) 
    - Read W&B 5:119-150
    - Read [W&B](http://behavioralneuroscience8e.com/) 11:337-347.
- Materials
    - [Slides](lectures/260-2021-11-04-sensation.html). [PDF](lectures/260-2021-11-04-sensation.pdf)
   
---

## Week 12, November 8 - 12

### Tuesday, November 9

- Topics
    - Wrap up on somatosensation
    - Action
- Assignments
- Materials
    - [Slides](lectures/260-2021-11-09-action.html). [PDF](lectures/260-2021-11-09-action.pdf)

### Thursday, November 11

- Topics
    - Wrap-up on action
    - Vision I
    - Review for Exam 3
- Assignments
    - Read W&B 7:183-201
- Materials
    - [Slides](lectures/260-2021-11-11-vision.html). [PDF](lectures/260-2021-11-11-vision.pdf)
    - [Exam 3 Study Guide](lectures/260-2021-11-11-exam-3-review.html)

---

## Week 13, November 15 - 29

### Tuesday, November 16

- Topics
    - **Exam 3**.

### Thursday, November 18

- Topics
    - Vision II
- Assignments
    - Read W&B 7:201-215.
- Materials
    - [Slides]()

---

## Thanksgiving Break

**NO CLASS**

---

## Week 14, November 29 - December 3

### Tuesday, November 30

- Topics
    - Learning & memory
- Assignments
    - Read W&B 13:379-391.
- **Papers or blog post #3 (of 3) due**. | [Blog assignment details](blog-assignment.html) | [Paper assignment details](paper-assignment.html) |
- Materials
    - [Slides]()

### Thursday, December 3

- Topics
    - Learning & memory II
- Assignments
    - Read W&B 13:392-401.
- Materials

---

## Week 15, December 6 - 10

### Tuesday, December 7

- Topics
    - **Quiz 4**.
    - Exam 3 discussion.
    - Speed of nervous system conduction lab

### Thursday, December 9

- Topics
    - Review for Exam 4
    - Frontiers & careers in neuroscience
    - The Cerebral Symphony
- Materials
    - [Exam 4 Study Guide]()

---
    
## Finals Week, December 14 - 18

### TBD

- Exam 4
